url_railstutorial: "https://www.railstutorial.org/"
url_railstutorial_book: "https://www.railstutorial.org/book"
url_screencasts: "http://screencasts.railstutorial.org/"
url_rubyonrails: "http://rubyonrails.org/"
url_railstutorial_help: "https://www.railstutorial.org/help"
url_railstutorial_contact: "https://www.railstutorial.org/contact"
