url_railstutorial: "https://www.railstutorial.org/"
url_railstutorial_book: "https://www.railstutorial.org/book"
url_screencasts: "http://screencasts.railstutorial.org/"
url_rubyonrails: "http://rubyonrails.org/"
url_railstutorial_help: "https://www.railstutorial.org/help"
url_railstutorial_contact: "https://www.railstutorial.org/contact"
url_michael_hartl: "http://www.michaelhartl.com/"
gravatar_img: "http://gravatar.com/emails"
max_name_length: 50
min_pass_length: 6
max_email_length: 255
size_gravatar: 50
gravatar_size: 50
quantity_per_page: 10
time_expired: 2
max_content_length: 140
size_picture: 5
limit_picture: [400, 400]
